name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - dev
jobs:
  check-application:
    strategy:
      matrix:
        go: ['1.14', '1.15']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }} 
      - run: go test
      - run: go run math.go
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: phelicio/ci:latest